set nocompatible

call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

filetype plugin indent on

" Enable/disable mouse
function! ToggleMouse()
  if &mouse == 'a'
    set mouse=
    echo "Mouse usage disabled"
  else
    set mouse=a
    echo "Mouse usage enabled"
  endif
endfunction
nnoremap <leader>m :call ToggleMouse()<CR>

" Avoid syntax-highlighting for files, larger than 100KB
autocmd BufReadPre * if getfsize(expand("%")) > 100*1024 | syntax off | endif

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Folding
if has('folding')
  set foldmethod=indent
  set foldlevel=99
  " toggle folds with space
  nmap <space> za
endif

set backspace=indent,eol,start

set enc=utf-8

set nobackup

set wildmenu

set number

set title
set ruler
set showcmd
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)

set scrolljump=5
set scrolloff=3

set incsearch
set showmatch
set hlsearch
set ignorecase
set smartcase
"Clear the search highlight by pressing ENTER when in Normal mode (Typing commands)
nnoremap <CR> :nohlsearch<CR>/<BS><CR>

set gdefault

set list listchars=tab:>·,trail:·

" Symbol "-" - part of word
set iskeyword+=-

set nowrap
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

vnoremap < <gv
vnoremap > >gv

" \p - toggle paste mode
set pastetoggle=<leader>p

" \w - toggle text wrapping
nmap <leader>w :set wrap! <CR>

" \l - toggle line numbers
nmap <leader>l :set number! <CR>

" \s - toggle syntax highlight
nmap <leader>s :if exists("g:syntax_on") <Bar>
    \   syntax off <Bar>
    \ else <Bar>
    \   syntax enable <Bar>
    \ endif <CR>

"Solarized
set t_Co=16
if has("gui_running")
    set t_Co=256
    let g:solarized_termcolors=256
endif

syntax enable
set background=dark
colorscheme solarized

" \b - toggle background color
call togglebg#map("<leader>b")

"FuzzyFinder
nnoremap <silent> ffb :FufBuffer<CR>
nnoremap <silent> fff :FufFile<CR>
nnoremap <silent> ffd :FufDir<CR>
nnoremap <silent> ffj :FufJumpList<CR>

" NERDTree
" \f - find file in NerdTree
" \t - just open NerdTree
nmap <leader>f :NERDTreeFind<CR>
nmap <leader>t :NERDTreeToggle<CR>
let NERDTreeShowBookmarks=0
let NERDTreeChDirMode=0
let NERDTreeQuitOnOpen=1
let NERDTreeShowHidden=1
let NERDTreeKeepTreeInNewTab=1

" Open a NERDTree automatically when vim starts up if no files were specified
autocmd vimenter * if !argc() | NERDTree | endif

command W w
command WQ wq
command Wq wq
command Q q
