#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Shortcuts
alias d="cd ~/Documents/Dropbox"
alias p="cd ~/Projects"
alias g="git"
alias h="history"
alias e="vim"
alias v="vim"
alias vim="vim -O"
alias s="subl ."
alias o="open"
alias oo="open ."
alias c='drawline'
alias reload='source ~/.bash_profile'
alias rel='reload'

alias h='fc -l'
alias m='less'

# GIT & SVN
alias gst='git st'
alias gs=gst

alias g1='git log -1'
#alias s1='svn log -l1'

# цветной diff git
gd()
{
    git diff "${@}" | colordiff
}
gds()
{
    git diff --staged "${@}" | colordiff
}
alias gdc=gds
alias sd='svn diff | colordiff'

# replace git read-only protocol to pushable ssh in current git repo
alias gitssh='sed -ie "s/git:\/\/\([^\/]*\)\/\(.*\)/git@\1:\2/g" .git/config'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
colorflag="--color"
else # OS X `ls`
colorflag="-G"
fi

# Listing
alias l="ls -l ${colorflag}"
alias ll="ls -laFo"
alias la="ls -la ${colorflag}"
alias lsd='ls -l ${colorflag} | grep "^d"'
alias ltr='ls -ltr'

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

export LS_COLORS='di=34:ln=35:ex=1;32:*.js=33:*.css=33:*.gz=31:*.tar=31:*.tgz=31:*.zip=31:*.bz2=31:*.deb=31:*.rpm=31:*.jar=31:*.png=32:*.jpg=32:*.jpeg=32:*.svg=32'

_expand()
{
    return 0;
}

# Misc
alias mine='sudo chown -R $USER:www .'

# Draws horizontal line and clears sreen
drawline()
{
    SEPARATOR="-"
    WIDTH=$(tput cols);
    echo -e "\033[$(($RANDOM % 7 + 31))m"
    ST=""
    for ((i=0; i<$WIDTH; i++)); do ST+=$SEPARATOR ; done
    echo $ST
    echo -e $RESET
    clear
}

# Universal make
if [[ `which gmake` != '' ]]; then
    alias make='gmake'
else
    alias gmake='make'
fi

# Universal ack
if [[ `which 'ack-grep'` != '' ]]; then
    alias ack='ack-grep'
fi

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ips="ifconfig -a | grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' | sed -e 's/inet6* //'"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'


