#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Shortcuts
alias d="cd ~/Documents/Dropbox"
alias p="cd ~/Projects"
alias g="git"
alias h="history"
alias j="jobs"
alias v="vim -o"
alias s="subl ."
alias o="open"
alias oo="open ."

alias h='fc -l'
alias m='less'
alias g='egrep -i'

# Universal make
if [[ `which gmake` != '' ]]; then
alias make='gmake'
else
alias gmake='make'
fi

# Git

alias ga='git add'
alias gb='git branch'
alias go='git checkout'
alias gi='git ci'
alias gd='git di'
alias gds='git di --staged'
alias gm='git merge --no-ff'
alias gs='git st'
alias gl='git lol'
alias gp='git pull --rebase'
alias gt='git tag'
alias gr='git remote -v'
alias gh='git hist'

alias sd='svn di | colordiff'
alias st='svn st'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
colorflag="--color"
else # OS X `ls`
colorflag="-G"
fi

# Listing
alias l="ls -l ${colorflag}"
alias ll="ls -laFo"
alias la="ls -la ${colorflag}"
alias lsd='ls -l ${colorflag} | grep "^d"'

# Always use color output for `ls`
alias ls="command ls ${colorflag}"

export LS_COLORS='di=34:ln=35:ex=1;32:*.js=33:*.css=33:*.gz=31:*.tar=31:*.tgz=31:*.zip=31:*.bz2=31:*.deb=31:*.rpm=31:*.jar=31:*.png=32:*.jpg=32:*.jpeg=32:*.svg=32'

_expand()
{
    return 0;
}