#!/usr/bin/env bash

declare -a files=(
    $HOME/dotfiles/bash/exports # Configuration
    $HOME/dotfiles/bash/aliases # Aliases
    $HOME/dotfiles/bash/vcs     # Version control aliases
    $HOME/dotfiles/bash/osx     # MacOS X customize
    $HOME/dotfiles/bash/network # Aliases for networking
    $HOME/dotfiles/bash/prompt # Custom bash prompt
    $HOME/dotfiles/git/git-completion.bash # Git tab-completion for bash
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/dotfiles/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    $HOME/dotfiles/bash/tmux # tmux / screen configs
    $HOME/dotfiles/bash/python # python configs
    $HOME/.rvm/scripts/rvm # Load Ruby RVM into a shell session *as a function*
    $HOME/dotfiles/yandex/functions # Yandex specific aliases & functions
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

# Show MOTD
if [ ! $silent ]; then
    drawline
    echo -e "\033[$(($RANDOM % 7 + 31))m"
    motd=($HOME/dotfiles/bash/motd/*)
    cat ${motd[RANDOM % ${#motd[@]}]}
    echo -e $RESET
fi

unset files

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$HOME/.cargo/bin:$PATH"

test -e ~/.iterm2_shell_integration.bash && source ~/.iterm2_shell_integration.bash || true
