#!/usr/bin/env bash

declare -a files=(
    $HOME/dotfiles/bash/exports # Configuration
    $HOME/dotfiles/bash/aliases # Aliases
    $HOME/dotfiles/bash/prompt # Custom bash prompt
    $HOME/dotfiles/git/git-completion.bash # Git tab-completion for bash
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/dotfiles/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

# Show MOTD
if [ ! $silent ]; then
    drawline
    echo -e "\033[$(($RANDOM % 7 + 31))m"
    motd=($HOME/dotfiles/bash/motd/*)
    cat ${motd[RANDOM % ${#motd[@]}]}
    echo -e $RESET
fi

unset files
