#!/usr/bin/env bash

export PATH=./node_modules/.bin:$PATH
export PATH=~/node_modules/.bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=~/bin:$PATH
export PATH=~/dotfiles/bin:$PATH
export PATH=~/dotfiles/yandex/bin:$PATH
export PATH=/usr/local/php5/bin:$PATH
export PATH=~/.rvm/bin:$PATH
export PATH=~/android-sdk-macosx/platform-tools:$PATH

export NODE_PATH="/usr/local/lib/node_modules"

export LC_ALL="ru_RU.UTF-8"
export LANG="ru_RU.UTF-8"
export EDITOR="vim"
export TERM="xterm-256color"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:ll:la:cd:cd -:pwd:exit:date:* --help:gst:gd:gds:sd:c:la:h"

HISTTIMEFORMAT='%F %T '
export HISTTIMEFORMAT

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
fi
