#!/usr/bin/env bash

# Tmux stuff
alias tm="tmux -2 -S /tmp/tm-`whoami`"

# Save ssh agent socket for using in tmux sessions
if [[ $SSH_AUTH_SOCK && `readlink ~/.ssh/ssh_auth_sock` != $SSH_AUTH_SOCK ]]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
